### ISSUE TITLE
Documentation for existing cluster monitoring

### ISSUE THREAD

**Issue by stationweb** [codership/galera-manager-support#1]
Hello, 

thank you for this new version, I confirm that I have successfully installed on debian 10! 

I want to monitor an existing cluster, would you have an updated documentation detailing the procedure (including ssh key configuration, location of the automatically generated key etc ...)

On the other hand, for security reasons, I wonder about the necessity of ssh access to the cluster node. 
Is ssh access necessary to monitor the vital signs of the node? 
Is this access only needed to eventually deploy a new node? 
Is it possible to configure a node without this ssh access which is mandatory in the procedure of adding a node (for example via a file configuration)?

Thanks in advance for your answer,

**Comment by denisvmedia** [comment]
Hello,

ssh access is required to install additional packages, which are required to export metrics and logs and send them to the Galera Manager daemon. Once the packages are installed, ssh access is not used anymore and can be restricted.

**Comment by stationweb** [comment]
Hi,

Thank you for your answer!
As you advised me, I opened the root login access via public key during the configuration. 
The procedure of adding the node worked without any problem and the monitoring works well.
