### ISSUE TITLE
Licensing details

### ISSUE THREAD

**Issue by nandithakd** [codership/galera-manager-support#101]
We need to use Galera Manager one of our production environment as commercial use. Could you please let us know will there be any cost incur for the same if we use Galera manager? or can we use it as a freeware?

**Comment by byte** [comment]
@nandithakd I believe that you've been given an answer via our sales team. You can use Galera Manager today, as freeware, there is no cost incurred. Whether this changes in the future, I can't tell you, but as of today, you can use it in production for commercial use.
