### ISSUE TITLE
package galera-manager

### ISSUE THREAD

**Issue by marziogia** [codership/galera-manager-support#104]
Hi,
i have problem installing galera manager on an Ubuntu 22.04 server or Debian;
the error encountered is "E: Unable to locate package galera-manager".

**Comment by marziogia** [comment]
Hi,
the same issue also occurs on a host clean where is installed centos. 
we have made many attempts and the result is always the same.

**Comment by PhilippP2604** [comment]
Hi Marziogia,

i have the same issue, even when deploying a new cluster from existing galera manager: https://github.com/codership/galera-manager-support/issues/105

seems like Galera Repos are broken.

**Comment by byte** [comment]
Yes, can verify there is an issue, working to fix it

**Comment by byte** [comment]
hi, this has now been fixed, thank you
