### ISSUE TITLE
Repositories seem to be broken

### ISSUE THREAD

**Issue by PhilippP2604** [codership/galera-manager-support#105]
Hi,

seems like there are issues with the Galera Repositories.

When I am downloading galera manager, latest version from the website, i get the error: Unable to locate package galera-manager

If i want to deploy a new cluster with an existing galera manager i get the error: Unable to locate package galera-manager-filebeat

This happens on Ubuntu 20.04 as well as 22.04 

I am using Galera Manager Version: 1.8.4.

about 4 weeks ago the last cluster deployment worked without any issue.

DB Engine is mysql 8.0 which gets deployed itself without any issue.

Let me know if you need further info for troubleshooting

**Comment by marziogia** [comment]
Hi PhilippP2604,

i have the same issue, I hope they resolve it soon.

**Comment by byte** [comment]
I can verify there is an issue

**Comment by PhilippP2604** [comment]
@byte any idea when this will be fixed?

**Comment by byte** [comment]
Hi @PhilippP2604 @marziogia this has been fixed, so please try again
