### ISSUE TITLE
Galera Manager installation is Failing

### ISSUE THREAD

**Issue by saji1511** [codership/galera-manager-support#107]
While trying to install Galera Manager on Ubuntu, the installation fails with the error shown below:

~$ gm-installer 
gm-installer: command not found
ubuntu@ip-172-31-86-18:~$ ./gm-installer install 
INFO[0000] OS Detected: Debian / Ubuntu / Linux / focal / 20.04 
ERRO[0000] failed to assert privileges: you must run this program as root 
ubuntu@ip-172-31-86-18:~$ sudo ./gm-installer install 
INFO[0000] OS Detected: Debian / Ubuntu / Linux / focal / 20.04 
Do you accept the License Agreement? [a] to accept; [r] to read agreement; or [n] to reject.
Your choice: a
GMD Package Repository URL (blank for default) [https://repo.galera-manager.com/nexus/repository/galera-manager-release-1804]: 
GMD Package Repository User (blank for public repository): 
GMD Admin User Login [admin]: admin
GMD Admin Password: 
Repeat your entry: 
By what domain name or an IP address this service will be reached?
(Note that an externally resolvable domain name is needed to use an external
Certificate Authority, otherwise we will have to resort to self-signed
certificates for SSL if encryption is required): 
Enter your domain name or IP of the server [3.85.138.28]: galera.rencommerce.com
Enable https? [y/N] y
Use LetsEncrypt Certbot to autogenerate the certificates [y/N]: y
▁INFO[0025] Stopping gmd service                         
INFO[0025] Executing: systemctl stop gmd                
INFO[0025] Stopping nginx service                       
INFO[0025] Executing: systemctl stop nginx              
INFO[0025] Stopping InfluxDB service                    
INFO[0025] Executing: systemctl stop influxdb           
INFO[0025] Updating the package index                   
INFO[0025] Executing: apt-get update                    
▌INFO[0087] add-apt-repository universe                  
INFO[0087] Executing: add-apt-repository universe       
▊INFO[0088] Updating the package index                   
INFO[0088] Executing: apt-get update                    
▊INFO[0150] Installing curl                              
INFO[0150] Executing: apt-get install -y curl           
▍INFO[0150] Installing jq                                
INFO[0150] Executing: apt-get install -y jq             
▎INFO[0150] Importing Galera GPG key                     
INFO[0150] Executing: apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA 
▊INFO[0151] Creating /etc/apt/auth.conf.d                
INFO[0151] Executing: mkdir -p /etc/apt/auth.conf.d     
INFO[0151] Adding galera-manager private apt repository 
INFO[0151] Adding influxdata private apt repository     
INFO[0151] Importing InfluxData GPG key                 
INFO[0151] Executing: bash -c 'curl -sL https://repos.influxdata.com/influxdata-archive_compat.key | apt-key add -' 
▉INFO[0151] Updating the package index                   
INFO[0151] Executing: apt-get update                    
▊INFO[0213] Updating the package index                   
INFO[0213] Executing: apt-get upgrade -y                
▏INFO[0213] Installing influxdb2                         
INFO[0213] Executing: apt-get install -y influxdb2      
▍INFO[0214] Installing nginx                             
INFO[0214] Executing: apt-get install -y nginx          
▉INFO[0214] Installing software-properties-common        
INFO[0214] Executing: apt-get install -y software-properties-common 
▆INFO[0214] Installing galera-manager                    
INFO[0214] Executing: apt-get install -y galera-manager 
▃INFO[0215] Got an error and attepts = 3                 
INFO[0215] Got execution failure, will retry (attempts left 2) 
▍INFO[0220] Executing: apt-get install -y galera-manager 
▋INFO[0220] Got an error and attepts = 2                 
INFO[0220] Got execution failure, will retry (attempts left 1) 
▊INFO[0225] Executing: apt-get install -y galera-manager 
▌INFO[0225] Got an error and attepts = 1                 
The installation log is located at /tmp/gm-installer.log
ERRO[0225] Failed to complete installation: command failed (stepName=__step_no_010, commandId=10, commandType=IncludeCommand): command failed (stepName=__step_no_001, commandId=1, commandType=ForeachCommand): command failed (stepName=, commandType=ExecCommand): exit status 100 

Looks like the repository does not exists any more:
deb https://repo.galera-manager.com/nexus/repository/galera-manager-release-1804 bionic main

Is there a workaround or a way to install Galera Manager directly without having to install it via the repo or installer?

Thanks

**Comment by arenner-git** [comment]
Hi, just observed the same problem during an apt update. I think the repo is just down. I also see the problem when trying to get mariadb updates (at least for version 10.6) from https://downloads.mariadb.com/MariaDB/

**Comment by arenner-git** [comment]
Could you try again now? Seems to me like the repo is reachable again!

**Comment by byte** [comment]
sorry but this was the repo breaking again. it is now fixed @arenner-git @saji1511
