### ISSUE TITLE
In-life OS support

### ISSUE THREAD

**Issue by victor-hotel** [codership/galera-manager-support#109]
This seems to only be supported on EoL linux distros.

Are there any plans for Rocky 9 or Debs Bookworm ?

**Comment by byte** [comment]
@victor-hotel Debian Bookworm = Debian 12 - it is supported

https://galeracluster.com/2024/03/galera-manager-march-2024-release-now-includes-ui-improvements-and-a-ssh-console-tab/

Rocky Linux 9 will not be supported, but Red Hat Enterprise Linux 8 is, and RHEL 9 will come as well

**Comment by victor-hotel** [comment]
Thank you @byte .
I must have misread the docs. I will use Debian 12.
Thanks for the prompt reply.
