### ISSUE TITLE
ask for how much disk space to allocate for /var/lib/mysql on nodes

### ISSUE THREAD

**Issue by stralytic** [codership/galera-manager-support#11]
By default when creating a node it allocates 80gig of disk space, which may not be enough.

I went into aws console and resized the disks and then sshed into each node and did xfs_growfs to workaround.

**Comment by denisgcm** [comment]
Thank you for reporting this. The feature is already developed and it will be supported in the next release.

**Comment by denisgcm** [comment]
The feature is present in 1.4.
