### ISSUE TITLE
allow using aws vpc backbone for cross region replication

### ISSUE THREAD

**Issue by stralytic** [codership/galera-manager-support#12]
would it be possible to create a cross region vpc in aws and use it for replicating data between regions instead of using public ip addresses and sending the data over the internet?

**Comment by satxroadrunner** [comment]
@stralytic This is possible as of now! A few things would be needed for this.. For example, 3 VPCs with a private subnet in each, VPC peering to each of the VPC's, security groups configured to allow communication on the desired ports. I can give more in-depth details if you'd like, but yes, this is VERY possible!
