### ISSUE TITLE
Problem installa galera manager on Ubuntu bionic

### ISSUE THREAD

**Issue by ptrujillo1976** [codership/galera-manager-support#18]
I have problem installing galera mamanger on Ubuntu bionic.
When execute installer I have this error:
ERRO[0043] command failed (stepName=install_curl, commandId=8, commandType=ExecCommand): exit status 100
![image](https://user-images.githubusercontent.com/97114306/148086627-dea67273-2842-4ba7-8caf-fe2d9d62d9b4.png)
When run "apt-get update" this is the error:
Err:4 https://repo.galera-manager.com/nexus/repository/galera-manager-release-1804 bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 134.209.245.63 443]
![error_apt](https://user-images.githubusercontent.com/97114306/148086763-dbfd76ae-836e-4549-a397-0768d4ed65eb.png)
Please help me.

**Comment by denisgcm** [comment]
Can you please try `apt-get update` & `apt-get upgrade` before running `gm-installer`? The problem may happen in older distributions because of this issue: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by ptrujillo1976** [comment]
> Can you please try `apt-get update` & `apt-get upgrade` before running `gm-installer`? The problem may happen in older distributions because of this issue: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Thank for reply. 

I can't run "apt-get upgrade" because I have other systems installed on the server that would stop working.
Is there a possibility to install gm manually?

**Comment by denisgcm** [comment]
In this case you need to update at least the certificates. Try running `update-ca-certificates`. Please let me let me know if it helped.

**Comment by ptrujillo1976** [comment]
the error still persists:
Err:10 https://repo.galera-manager.com/nexus/repository/galera-manager-release-1804 bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 134.209.245.63 443]

**Comment by denisgcm** [comment]
You can try bypassing the security mechanism:

```bash
touch /etc/apt/apt.conf.d/99verify-peer.conf
echo >> /etc/apt/apt.conf.d/99verify-peer.conf "Acquire { https::Verify-Peer false }"
```

And retry the installation. Note, this will effectively turn off https peer verification, which might make apt vulnerable for the MitM attacks.

**Comment by ptrujillo1976** [comment]
Thank denisgcm for your help. 
I decided install GM on Ubuntu 20 and there I have had no problems.
