### ISSUE TITLE
Can't set trx_fragment_size to values >0

### ISSUE THREAD

**Issue by preimann01** [codership/galera-manager-support#22]
I have a galera 4 cluster with two MySQL 8 nodes and garbd. I would like to test the new streaming replication feature but can't enable it.
I do not use MariaDB which is found in most of the documentation for this feature. Isn't it available for MySQL 8?

wsrep_provider -> /usr/lib64/galera-4/libgalera_smm.so
mysql -> 8.0.25 MySQL Community Server

SET SESSION wsrep_trx_fragment_size=1;
ERROR 1231 (42000): Variable 'wsrep_trx_fragment_size' can't be set to the value of '1'
SET SESSION wsrep_trx_fragment_size=0;
Query OK, 0 rows affected (0,01 sec)

**Comment by denisgcm** [comment]
This repo is only for the issues related to Galera Manager. Try asking [here](https://github.com/codership/galera/issues).
