### ISSUE TITLE
Latest (Feb 2022) release does not support Debian 11

### ISSUE THREAD

**Issue by khoosys** [codership/galera-manager-support#25]
Created a new debian 11 VM. 
Downloaded latest gm-installer
root@xx:~# ./gm-installer version
gm-installer version 1.6.0 (linux/amd64)

At the end of run says:

ERRO[0019] unsupported os

Article
https://galeracluster.com/2022/02/galera-manager-february-2022-release/

Says this version is the latest Feb release and that Debian 11 is supported

**Comment by denisgcm** [comment]
Thank you for reporting this. Current Galera Manager release supports Debian 11 on the nodes, but the GM installer still doesn't. We'll release a new version of the installer soon, which will support Debian 11.

**Comment by denisgcm** [comment]
The latest version of the installer now supports Debian 11.

**Comment by ayurchen** [comment]
The latest version of installer supports Deb 11 now
