### ISSUE TITLE
Cannot install gm on host with disabled SELinux

### ISSUE THREAD

**Issue by peter-reimann-1** [codership/galera-manager-support#27]
I have a test host (CentOS 7) with SELinux disabled. The just (2022-03-03) downloaded gm-installer breaks out due to sentenforce comes back with 1 (SELinux disabled)

The log is not helpfule at all:

```
setenforce: SELinux is disabled
```

This is all what is inside the log :-(. How to deal with it?

**Comment by ronnybremer** [comment]
The only workaround is to enable SELinux (/etc/selinux/config -> change to Enforce), then reboot the system, afterwards the installer will continue and funny enough, disable SELinux again. Apparently there is no check for SELinux already being disabled during the installation.

**Comment by celldara** [comment]
the installer has 0 checks and just does stuff.  Not very professional at all.

**Comment by denisgcm** [comment]
Thank you for reporting it. We currently only support fresh non-customized OS installations (i.e. the ones freshly installed and not customized by the user). This particular issue however will be solved in the next releases of `gm-installer`.
