### ISSUE TITLE
First attempt fails when adding new node (monitoring context)

### ISSUE THREAD

**Issue by stationweb** [codership/galera-manager-support#3]
Hello, 

I have identified a problem when adding a new node in a cluster monitoring context.
Debian 10 / Mariadb 10.3

The first attempt fails:
![error](https://user-images.githubusercontent.com/5964050/132205434-3d361bf7-3112-4713-a9f6-e75315e000f4.png)

The log says: 
{"channel-type":"app","cluster-id":"6","file":"/go/pkg/internal/mgmt/units/node.go:829","func":"github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Node).saveDeploymentInfo","host-id":"5","level":"error","msg":"failed to execute cluster config script (RunScriptWithConn): command failed (stepName=__step_no_001, commandId=1, commandType=IncludeCommand): command failed (stepName=__step_no_004, commandId=4, commandType=IncludeCommand): command failed (stepName=create_mysqld_exporter_user, commandId=1, commandType=ExecCommand): failed to set ssh environment variable: ssh: setenv failed","node-id":"5","time":"2021-09-06T12:36:02+02:00"}

To restart the attempt, I delete the file /etc/galera-manager-node, I do not change anything between the two attempts.

The second attempt succeeds:
![success](https://user-images.githubusercontent.com/5964050/132205745-4892eb7c-b636-4276-94a3-5bf9a2beb59b.png)

**Comment by denisvmedia** [comment]
Thanks for reporting this. We add `AcceptEnv MYSQL_PWD` var to sshd_config and it may have happened that the sshd daemon reload didn't finish before we attempted to do the rest. We will investigate this issue.

**Comment by stationweb** [comment]
I didn't see your answer before testing on another node. 
By adding AcceptEnv MYSQL_PWD by hand, before running the procedure, the node is added successfully on the first attempt.

**Comment by denisgcm** [comment]
Thank you for your report. We solved this issue. The fix will be included in the next update.
