### ISSUE TITLE
gmc version 1.5.0 - cannot deploy nodes - debian 11

### ISSUE THREAD

**Issue by khoosys** [codership/galera-manager-support#30]
- clean installed latest gmc version 1.5.0 on deb 11
- launch web interface
- add node - select a clean install deb 11 server with mariadb on it
- check access all ok 
- press install and then the interface shows login screen
- log back in and node is in stray hosts - pending. Never gets added.
- delete this node - on pressing the confirmation button again throws you back to the login screen. Node is not deleted.
- force delete works ok

**Comment by alex0107** [comment]
Same problem here

**Comment by ayurchen** [comment]
Will be fixed in the next release.

**Comment by FinalTek** [comment]
Same [problem here](https://zed.finaltek.net/gmd/gmd-deb11-deploy-host-error.png). gm-installer 1.8.0, clean hosts with fresh Deb 11.3 install. Please help!

**Comment by ayurchen** [comment]
@FinalTek Hi, what's the version of Galera Manager? Just yesterday we made a new release. Could you try `apt update; apt upgrade` ?

**Comment by alex0107** [comment]
Debian 11 still not working but there is now an error message:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/17063865/167011141-1caebf2e-f515-4d57-a0ea-2af0ffe76853.png">

**Comment by ApertureDevelopment** [comment]
> @FinalTek Hi, what's the version of Galera Manager? Just yesterday we made a new release. Could you try `apt update; apt upgrade` ?

I have the same issue as @FinalTek  using Galera Manager 1.6.4 ( gm-installer 1.8.0 ). I always get the response of an unsuported operating system using debian 11 and mariadb 10.6

**Comment by ayurchen** [comment]
Fixing this issue in the next release.

**Comment by justnx** [comment]
It seems the deploy process is looking for galera-3 package version number instead galera-4 which is default since mariadb 10.5.
Is there any ETA or Beta for the fixed release?

**Comment by justnx** [comment]
Just upgraed to galera-manager 1.7.1 and now im getting this:

``{"channel-type":"app","file":"/go/pkg/internal/sshcmd/host.go:254","func":"github.com/codership/galera-manager/pkg/internal/sshcmd.(*Host).RunConn","host-name":"galera-1","level":"info","msg":"root@galera-1# echo -n \"test\"","time":"2022-09-27T11:48:58+02:00"}
{"channel-type":"stdout","file":"/go/pkg/log/iolog.go:37","func":"github.com/codership/galera-manager/pkg/log.(*IOLog).Write","host-name":"galera-1","level":"info","msg":"test","time":"2022-09-27T11:48:58+02:00"}
{"channel-type":"app","error":{"msg":"failed to execute info script","stackTrace":["github.com/codership/galera-manager/pkg/internal/mgmt.(*Checker).CheckServerAccess.func1\n\t/go/pkg/internal/mgmt/checker.go:127","github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:90","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"],"wrapped":{"msg":"failed to load executor","stackTrace":["github.com/codership/galera-manager/pkg/internal/sshcmd.(*Host).RunScriptWithConnNoDB\n\t/go/pkg/internal/sshcmd/executor.go:150","github.com/codership/galera-manager/pkg/internal/mgmt.(*Checker).CheckServerAccess.func1\n\t/go/pkg/internal/mgmt/checker.go:118","github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:90","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"],"wrapped":{"msg":"invalid command type: \"box_include\"","stackTrace":["gitlab.galeracluster.com/lib/executor.(*Executor).AppendScenario\n\t/go/.go/pkg/mod/gitlab.galeracluster.com/lib/executor@v1.22.0/executor.go:318","gitlab.galeracluster.com/lib/executor.NewWithScenario\n\t/go/.go/pkg/mod/gitlab.galeracluster.com/lib/executor@v1.22.0/executor.go:181","github.com/codership/galera-manager/pkg/internal/sshcmd.(*Host).RunScriptWithConnNoDB\n\t/go/pkg/internal/sshcmd/executor.go:138","github.com/codership/galera-manager/pkg/internal/mgmt.(*Checker).CheckServerAccess.func1\n\t/go/pkg/internal/mgmt/checker.go:118","github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:90","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"]}},"fields":{"db_engine":"","system":"debian:11"}},"file":"/go/pkg/internal/mgmt/checker.go:133","func":"github.com/codership/galera-manager/pkg/internal/mgmt.(*Checker).CheckServerAccess.func1","host-name":"galera-1","level":"error","msg":"failed to execute info script","time":"2022-09-27T11:48:58+02:00"}
{"channel-type":"app","file":"/go/pkg/internal/sshcmd/host.go:254","func":"github.com/codership/galera-manager/pkg/internal/sshcmd.(*Host).RunConn","host-name":"galera-1","level":"info","msg":"root@galera-1# echo -n \"test\"","time":"2022-09-27T11:49:52+02:00"}
{"channel-type":"stdout","file":"/go/pkg/log/iolog.go:37","func":"github.com/codership/galera-manager/pkg/log.(*IOLog).Write","host-name":"galera-1","level":"info","msg":"test","time":"2022-09-27T11:49:52+02:00"}
``
Sep 27, 2022 11:49:53 | info    | root@galera-1# echo -n "test"
Sep 27, 2022 11:49:53 | info    | test
Sep 27, 2022 11:49:53 | error   | failed to execute info script

And im wondering why it let me configure "EC2 Security Groups" when deploying cluster in user-provided-hosts mode.

**Comment by denisgcm** [comment]
It should be already fixed. Please re-open, if the problem still persists.
