### ISSUE TITLE
Oracle Linux Server 8.5 compatibility issue

### ISSUE THREAD

**Issue by thiagocostatrt14** [codership/galera-manager-support#32]
**Cluster database engine:** MariaDB 10.6.5

**Galera Manager version used:** 1.6.2

**Browser used:** Google Chrome 101.0.4951.54 (official version) 64 bits

**Galera Manager host OS:** Oracle Linux Server 8.5

**Cluster Host OS:** Oracle Linux Server 8.5

**Cluster node:** Unmanaged

**Problem type:** OS compatibility 

**Problem description:** When configuring the nodes of my Galera Cluster on the Galera Manager, it says there is a compatibility problem between the Galera Manager and the OS of the nodes I want to manage.
My cluster consists of three VM with Oracle Linux Server 8.5, an OS apparently not supported in Galera Manager... But it is RedHat 8 compatible, right?
Since I could install the Galera Manager on a machine with the same OS with no errors and the problem happens when I am trying to add a node to the monitoring, is there a way to workaround this issue?

Checking connection:
![access_check](https://user-images.githubusercontent.com/105362523/167849045-7204cbd7-90d1-4580-986f-0a6750905f60.png)

Compatibility Error:
![error](https://user-images.githubusercontent.com/105362523/167849078-35c4a8a4-fded-4a53-a98d-8bcdce993560.png)

**Comment by denisgcm** [comment]
It is a bug, which will be fixed in the next release.

**Comment by denisgcm** [comment]
It should be already fixed in the most recent version of Galera Manager.
