### ISSUE TITLE
Custom DB engine configuration not available on "User-provided hosts" clusters

### ISSUE THREAD

**Issue by vztaurelio** [codership/galera-manager-support#35]
When you deploy a new cluster with user provided hosts, the "Custom DB engine configuration" is not available. 
As the DB engine installation in the node is managed by Galera Manager, there is no easy option to modify its configuration.

**Comment by mihaellenic** [comment]
Thank you for reporting this. It will be fixed in the next release, will update this ticket when the release is out.

**Comment by mihaellenic** [comment]
Fixed and released in a v1.7.0

**Comment by m7mdcc** [comment]
Sorry to bump this, but I want to ask if we able to change this custom configuration after deploying the nodes.

![Image](https://github.com/user-attachments/assets/afbf86f0-432b-444e-bac0-01996d83ccb2)


Where is the file where I can change the configuration for each node? Is it /etc/mysql/wsrep/conf.d/99.galera.cnf ?
