### ISSUE TITLE
MySQL Runs on 3306 During State Transfer Then to Custom Port

### ISSUE THREAD

**Issue by bbuchan10** [codership/galera-manager-support#36]
Hi, I am running a three node Galera MySQL cluster. I have changed the MySQL port from 3306 to 3360 because I am running the Galera Cluster also on the same hosts as my 3 node Docker Swarm (Galera is not running as a container but rather on the host itself). My Docker cluster is also running the HAProxy load balancers and therefore listening on 3306 then backend is pointed to the 3360. This should all work, except what I am seeing is that MySQL/WSREP is trying to start on 3306 to perform the state transfer, then it switches to the custom port afterward. Is this a bug? Or is this just unavoidable?

**Comment by denisgcm** [comment]
I believe, this issue is unrelated to Galera Manager. You should report this in the corresponding repository.
