### ISSUE TITLE
Nodes created on AWS with security groups but don't join

### ISSUE THREAD

**Issue by richardhowes** [codership/galera-manager-support#37]
Hi All,

I have successfully created an AWS instance of Ubuntu 18.04 and installed Galera Manager. Then I get GM to create a cluster and three cluster nodes. So I end up with 4 instances, the GM and the three nodes. This works perfectly.

![Screenshot from 2022-07-28 14-04-29](https://user-images.githubusercontent.com/7155961/181525766-3b9ab65c-d27e-4a15-b254-daf215e24272.png)

I end up with a cluster and the three nodes, but they don't connect. It seems like the Security Groups on AWS are correct, but to be sure I opened up All Traffic, inbound and outbound, on all four instances. So I'm fairly sure the problem is not AWS security.

![Screenshot from 2022-07-28 14-04-52](https://user-images.githubusercontent.com/7155961/181527156-aa1597e9-3c18-4830-886b-f987e6f231dd.png)

I can SSH into all four nodes and MariaDB is installed and running (I can log in with 'mysql').

I am using Ubuntu 18.04 and MariaDB 10.3.

If anyone can assist I would be very appreciative. Galera Manager seems like the perfect tool, and I get so very close to success and then the cluster does not connect/work.

Thank you!

**Comment by richardhowes** [comment]
I have found more information. There is the following error (multiple times) in the syslog:

"2022-07-28T14:42:02Z W! [outputs.influxdb] When writing to [https://custom.domain.net:9091]: database "gmd" creation failed: Post "https://custom.domain.net:9091/query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

And from this it seems INFLUXDB is a problem. The URL to access the gm database doesn't seem to work either.

Hope that info helps.

**Comment by ayurchen** [comment]
Hello Richard,
Can you log in to MYSQL instance? What does
```
mysql> SHOW GLOBAL VARIABLES LIKE 'wsrep%';
```
say?
What is Galera Manager version you ended up using?

**Comment by richardhowes** [comment]
Hi Alexey,

Thank you so much for responding. I am using Galera Manager 1.6.4 and the wsrep variables are below.

Thank you.
Richard

Variable_name                    		Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             wsrep_osu_method                 	TOI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_sr_store                   		table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             wsrep_auto_increment_control    	ON                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
wsrep_causal_reads               	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_certification_rules        	strict                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           wsrep_certify_nonpk              	ON                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
wsrep_cluster_address            	gcomm://13.244.76.15,13.246.139.91                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
wsrep_cluster_name               	RR Enterprise                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
wsrep_convert_lock_to_trx        	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_data_home_dir              	/var/lib/mysql/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wsrep_dbug_option                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wsrep_debug                      		NONE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
wsrep_desync                     		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               wsrep_dirty_reads                		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_drupal_282555_workaround  	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_forced_binlog_format       	NONE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
wsrep_gtid_domain_id             	0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_gtid_mode                  		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_ignore_apply_errors        	7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_load_data_splitting        	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_log_conflicts              		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_max_ws_rows                	0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_max_ws_size                	2147483647                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
wsrep_mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         wsrep_mysql_replication_bundle   	0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_node_address                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_node_incoming_address      AUTO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
wsrep_node_name                  	node-voihz                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
wsrep_notify_cmd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
wsrep_on                         		ON                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
wsrep_patch_version              	wsrep_26.22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
wsrep_provider                   		/usr/lib/galera/libgalera_smm.so                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wsrep_provider_options           base_dir = /var/lib/mysql/; base_host = 172.31.23.157; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.causal_keepalive_period = PT1S; evs.debug_log_mask = 0x1; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.info_log_mask = 0; evs.install_timeout = PT7.5S; evs.join_retrans_period = PT1S; evs.keepalive_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.use_aggregate = true; evs.user_send_window = 2; evs.version = 1; evs.view_forget_timeout = P1D; gcache.dir = /var/lib/mysql/; gcache.keep_pages_size = 0; gcache.keep_plaintext_size = 128M; gcache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 128M; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.fc_single_primary = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.listen_addr = ssl://0.0.0.0:4567; gmcast.mcast_addr = ; gmcast.mcast_ttl = 1; gmcast.peer_timeout = PT3S; gmcast.segment = 0; gmcast.time_wait = PT5S; gmcast.version = 0; ist.recv_addr = tcp://13.245.16.58; ist.recv_bind = tcp://0.0.0.0; pc.announce_timeout = PT3S; pc.checksum = false; pc.ignore_quorum = false; pc.ignore_sb = false; pc.linger = PT20S; pc.npvo = false; pc.recovery = true; pc.version = 0; pc.wait_prim = true; pc.wait_prim_timeout = PT30S; pc.weight = 1; protonet.backend = asio; protonet.version = 0; repl.causal_read_timeout = PT30S; repl.commit_order = 3; repl.key_format = FLAT8; repl.max_ws_size = 2147483647; repl.proto_max = 10; socket.checksum = 2; socket.recv_buf_size = auto; socket.send_buf_size = auto; socket.ssl = YES; socket.ssl_ca = /etc/mysql/wsrep/ssl/gmca.pem; socket.ssl_cert = /etc/mysql/wsrep/ssl/gmnode.pem; socket.ssl_cipher = ; socket.ssl 
wsrep_recover                    		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_reject_queries            	 	NONE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
wsrep_replicate_myisam           	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_restart_slave              		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_retry_autocommit           	1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_slave_fk_checks            	ON                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
wsrep_slave_uk_checks            	OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_slave_threads              	1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_sst_auth                   		********                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
wsrep_sst_donor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
wsrep_sst_donor_rejects_queries  OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_sst_method                 	mariabackup                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
wsrep_sst_receive_address        	13.245.16.58                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
wsrep_start_position             		00000000-0000-0000-0000-000000000000:-1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
wsrep_strict_ddl                 		OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
wsrep_sync_wait                  		0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_trx_fragment_size          	0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
wsrep_trx_fragment_unit          	bytes

**Comment by richardhowes** [comment]
Hi All,

During my investigation I discovered something very interesting. Galera Manager actually **_does_** set up the cluster successfully. I assumed it wasn't working because the manager said the nodes where not joined, however I created a new database on one of the nodes and it was replicated to the other nodes, so it's definitely working.

Interesting and still baffling that the cluster was set up by Galera Manager but the GM is not able to manage it. Different problem that still needs to be solved, but very interesting and may give more clues. I would still like to use GM, so this issue is not resolved. 

Thank you.
Richard

**Comment by denisgcm** [comment]
It's probably because InfluxDB is not available. InfluxDB is used by GMD to monitor the nodes and to check their status. If the problem is still actual, can you please check if gmd host has a port 8081 allowed (or 9091 in case of https used).
