### ISSUE TITLE
SSH Connection Status error while adding node to Cluster

### ISSUE THREAD

**Issue by azrulanuar** [codership/galera-manager-support#44]
Hi Support,

I've already establish a set of steps before this and there is no issue arise upon installing, creating a cluster and add up to 3 nodes. Recently, i stumble upon an issue even though its a same steps. The steps are as below

GM Host VM (Ubuntu 20.04)
1. Disable UFW
2. Disable AppArmor
3. Download and Install gm-installer
4. Log in to GM Web
5. Create Unmanaged Cluster
6. Added key to Node
7. Add Node (issue started happening)
8. Error Popup with text 'SSH Connection Status'

Cluster Node (Ubuntu 20.04) 
1. Disable UFW
2. Disable AppArmor
3. Add key to /root/.ssh/authorized_keys
4. Reboot

All host and nodes are clean install. No prior application installed before. 
Error in System Log tab is "failed to execute info script". However the echo test is successful. 

Please advise.

Info on the system and VM used
Cluster database engine - MySQL 8
Galera Manager - Version 1.7.2
Browser Used - Chrome
Galera Manager Host - Ubuntu Server 20.04 (tried with 22.04, gotten same result)
Cluster Host OS - Ubuntu Server 20.04 (tried with 22.04, gotten same result)
Cluster Node - Unmanaged

**Comment by waffle-stomper** [comment]
Duplicate of #41?

**Comment by azrulanuar** [comment]
sorry my bad, will close this and wait for update on #41
