### ISSUE TITLE
Unable to copy public key from the gui

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#46]
Version 1.7.3 of the GUI

Try to create a "deploy cluster on user provided hosts"

Aim to click copy. It does not copy to clipboard with a failure message - "Couldn't copy public key". 

Chrome. macOS. 
<img width="1332" alt="Screenshot 2022-12-07 at 23 00 54" src="https://user-images.githubusercontent.com/61067/206214764-0360feb9-5d1c-481c-b49b-cf2a379b8451.png">

**Comment by byte** [comment]
Upon further checking, you can see there is a different error message - "Couldn't copy public key because the application is not served over HTTPS"

<img width="1296" alt="Screenshot 2022-12-07 at 23 10 58" src="https://user-images.githubusercontent.com/61067/206216181-0e8cc173-3781-4b72-821d-d5d27695b03b.png">

Error messages need standardising.

Why is copying disabled over HTTP?

**Comment by mihaellenic** [comment]
Thank you for reporting. We have standardized messages now.

Copying is disabled because of security reasons. To prevent any malicious code from getting into the clipboard since HTTP is unsecured.

You can always manually select and copy the key.
