### ISSUE TITLE
FR: advanced option to run apache2 instead of nginx

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#5]
let the user run apache2 on port 80 and let Galera Manager work instead of nginx

in parallel, let Galera Manager be installed on a machine that also has existing software

(seems that the installer didn't check to see if port 80 was already being used by something else, thus maybe causing a silent failure)

see: https://groups.google.com/g/codership-team/c/mx72_yG-_9s/m/85ei-rNhAwAJ?utm_medium=email&utm_source=footer

**Comment by denisgcm** [comment]
There are currently no plans to support any pre-existing server installations (the installer expects a clean OS installation). But we will soon prepare a tutorial on how to install and configure `gmd` (Galera Manager Daemon) manually.

**Comment by denisgcm** [comment]
JFYI @byte, the most recent installer version now includes necessary port availability checks. As such, if you have any of the required ports occupied before the installer runs, the installer will now report that as an error and abort the installation.

**Comment by denisgcm** [comment]
Following up.

We are not going to officially support Apache web server at the moment, however, it is possible to have a combination of Apache and dockerized Galera Manager (see #7).

```
Listen 443
Listen 9096

NameVirtualHost *:443
<VirtualHost *:443>
    SSLEngine On

    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    SSLCertificateFile /etc/apache2/ssl/file.pem

    # Proxy connection to Galera Manager
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>

NameVirtualHost *:9096
<VirtualHost *:9096>
    SSLEngine On

    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    SSLCertificateFile /etc/apache2/ssl/file.pem

    # Proxy connection to Influx
    ProxyPass / http://127.0.0.1:8086/
    ProxyPassReverse / http://127.0.0.1:8086/
</VirtualHost>
```
