### ISSUE TITLE
when ssh needs upgrading (apt-get upgrade -y) does not work

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#6]
basically, when you install gm-installer install and ssh needs upgrading... ubuntu 20.04 lts and also ssh requires interactivity (dpkg unlike rpm can offer interactive -- gm-installer does not allow for interactivity, hence the breakage)

also, the lack of a status update, really hurts the UX.

▉ 2021/10/07 03:38:31 INFO: Upgrading system
2021/10/07 03:38:31 INFO: Executing: apt-get upgrade -y
▎ 
▋ 
▊ 
█ 
▇ 
▆ ^C
root@testgmubuntu:~# date
Thu Oct  7 04:07:07 UTC 2021

see the long pause? 3:38:31 to 4:07:07.

no user will wait this long and will stop the process

root@testgmubuntu:/var/log/apt# apt-get upgrade -y
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 9682 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
root@testgmubuntu:/var/log/apt# apt-get upgrade -y
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 9682 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
root@testgmubuntu:/var/log/apt# ps auxw|grep -i apt-get
root        9682  0.2  6.2  74792 63180 pts/0    S    03:38   0:03 apt-get upgrade -y
root       14176  0.0  0.2   8160  2596 pts/2    S+   04:06   0:00 grep --color=auto -i apt-get
root@testgmubuntu:/var/log/apt# kill -9 9682
root@testgmubuntu:/var/log/apt# apt-get upgrade -y
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
root@testgmubuntu:/var/log/apt# dpkg --configure -a
Setting up openssh-server (1:8.2p1-4ubuntu0.3) ...
rescue-ssh.target is a disabled or a static unit, not starting it.
Setting up shim-signed (1.40.7+15.4-0ubuntu9) ...

fix the manual install, then restart gm-installer install and things work

so today, we found an offending SSH package update. what else might we find?

**Comment by denisgcm** [comment]
> (dpkg unlike rpm can offer interactive -- gm-installer does not allow for interactivity, hence the breakage)

`gm-installer` due to its nature is not supposed to have interactions after you answered all the pre-installation questions. In most of the cases we forced unattended installation for the deb packages.

As for the progress, there is an indicator that something is running. If you want to have a textual output, you should run `./gm-installer --show-command-output` it will print out everything that is happening behind the scenes.

That said, I'm not sure there is something broken in the application according to your report. If you still think it is, please clarify what interactive command was required to run (unfortunately, I can't see that in your report - what I can see is that you interrupted the initial installation but that doesn't necessarily mean that the installer was stuck due to interaction required). You can also check `/tmp/gm-installer.log` for the full installation log.

**Comment by byte** [comment]
> > (dpkg unlike rpm can offer interactive -- gm-installer does not allow for interactivity, hence the breakage)
> 
> `gm-installer` due to its nature is not supposed to have interactions after you answered all the pre-installation questions. In most of the cases we forced unattended installation for the deb packages.

i believe this is really what users want; they do not want interactivtiy

the way to reproduce is hit a dpkg that requires it, e.g. ssh during the massive apt upgrade

 
> As for the progress, there is an indicator that something is running. If you want to have a textual output, you should run `./gm-installer --show-command-output` it will print out everything that is happening behind the scenes.

--show-command-output is not supported

./gm-installer 
Please specify one command of: certificates, install, uninstall or version
[root@gm ~]# ./gm-installer --show-command-output
unknown flag `show-command-output'

gm-installer version 1.3.0 (linux/amd64)

./gm-installer version --show-command-output
unknown flag `show-command-output'

it may work as ./gm-installer install --show-command-output but i did not have time to verify it

> That said, I'm not sure there is something broken in the application according to your report. If you still think it is, please clarify what interactive command was required to run (unfortunately, I can't see that in your report - what I can see is that you interrupted the initial installation but that doesn't necessarily mean that the installer was stuck due to interaction required). You can also check `/tmp/gm-installer.log` for the full installation log.

application isn't broken. application meets interactivity of a dpkg update, and you will see failure. you just haven't seen failure because you haven't encountered a package that will have an interactive update yet in your testing

the initial installation was of course stuck while dpkg was updating

**Comment by denisgcm** [comment]
Unattended installation should be now fixed with the version 1.4.0 of `gm-installer`.

**Comment by byte** [comment]
@denisgcm let me know when i can try this, or is it already pushed to public?

**Comment by denisgcm** [comment]
@byte yes, it's released publicly.
