### ISSUE TITLE
FR: allow galera manager to run inside of docker

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#7]
create a galera manager that runs inside of docker and can also deploy instances inside dockerised containers.

**Comment by denisgcm** [comment]
There are no obstacles to run `gmd` (Galera Manager Daemon) inside Docker even for the current release. We will soon prepare an official manual how to do that.

**Comment by denisgcm** [comment]
We will release an official solution later, but for now one can use this temporary solution: [gmd-in-docker.zip](https://github.com/codership/galera-manager-support/files/7533414/gmd-in-docker.zip)

**Comment by gregfr** [comment]
Greetings
Any news on official support of the manager in docker?
Regards

**Comment by roberto-maggi** [comment]
greetings,
I'm having some problems with the dockerized app,
it doesn't work at all if I change the admin password for the galera manager and for the gdm user in fluxdb 
and if I keep  them  it turns up butr I can't change the admin password through the galera cluster manager gui.
This is an actual problem, is there any solution?

**Comment by roberto-maggi** [comment]
HI you all,
why can't I change the passwords both through docker-compose files and via guy?
whenever I do that the services doesn't rise up

**Comment by Dmitry9292** [comment]
Seems like this gmd in docker is not working properly since once you stop the container, then you cannot start it again.
It keeps asking to reinit db or regenerate rsa key.
