### ISSUE TITLE
MariaDB 10.11 has Debian 12 binaries, but somehow is unsupported

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#73]
Galera Manager (1.8.0) installs on debian 12 with gm-installer version 1.11.0 (linux/amd64)

However, it falsely states that Debian 12 is unsupported to deploy the MariaDB 10.11 server

Debian 12 "bookworm" is supported by MariaDB Server 10.11
(see the repo chooser tool https://mariadb.org/download/?t=repo-config&d=Debian+12+%22Bookworm%22&v=10.11&r_m=osuosl)

Please fix so that one can use Galera Manager to deploy on Debian 12 baseOS, MariaDB 10.11 nodes.

<img width="1091" alt="Screenshot 2023-12-02 at 01 20 43" src="https://github.com/codership/galera-manager-support/assets/61067/d9f59561-b9fa-4d4d-9c4a-f0320c673e82">

**Comment by byte** [comment]
FYI, next release of 8.0 (8.0.35) will also include such support

**Comment by cybern0id** [comment]
Hoping this might be fixed soon!

**Comment by byte** [comment]
This is already fixed, so closing as such. 
<img width="920" alt="Screenshot 2024-03-26 at 08 20 35" src="https://github.com/codership/galera-manager-support/assets/61067/43ba8588-9b93-40dd-8047-47968f882c42">
