### ISSUE TITLE
Telegraf fails to start after update to 1.29.0-1

### ISSUE THREAD

**Issue by arenner-git** [codership/galera-manager-support#78]
Hi,

after updating packages (including telegraf update to 1.29.0-1) on one of our cluster nodes, I noticed, that the node seemed to be offline in galera manager (greyed out icon). I've checked the systemd status and saw, that an error prevents the telegraf service from starting:

`telegraf[1537395]: 2023-12-12T08:45:14Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.procstat: line 21: configuration specified the fields ["systemd_unit"], but they weren't used`
`systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE`

After downgrading back to 1.28.5-1 everyhting worked fine again.

Maybe this has something to do with the changes in telegraf. See [here](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md) and [here](https://github.com/influxdata/telegraf/pull/14224) as "input.procstats" is mentioned here explicitely I would consider that a possibility.

**Comment by byte** [comment]
Can verify that telegraf is broken at this very moment, thanks to a new release.

**Comment by byte** [comment]
@arenner-git can you check again? It looks like 1.29.0 broke it, but 1.29.1 fixed it.

dpkg -l|grep telegraf
ii  telegraf                           1.29.1-1                          amd64        Plugin-driven server agent for reporting metrics into InfluxDB.

going to guess it was this that caused it: https://github.com/influxdata/telegraf/pull/14440

**Comment by arenner-git** [comment]
> @arenner-git can you check again? It looks like 1.29.0 broke it, but 1.29.1 fixed it.
> 
> dpkg -l|grep telegraf ii telegraf 1.29.1-1 amd64 Plugin-driven server agent for reporting metrics into InfluxDB.
> 
> going to guess it was this that caused it: [influxdata/telegraf#14440](https://github.com/influxdata/telegraf/pull/14440)

@byte thx for the info. I can confirm: no problems with this version!
