### ISSUE TITLE
FR: support Debian 11 as an install OS

### ISSUE THREAD

**Issue by byte** [codership/galera-manager-support#8]
Debian 11, bullseye, is now released, and we have user requests for it to be supported as an install target. Please add this, thank you. 

https://www.debian.org/News/2021/20210814

**Comment by denisgcm** [comment]
Unfortunately, there is a lack of support from Galera Cluster itself for Debian 11, e.g. no release file for this distribution for MySQL 8.0: http://releases.galeracluster.com/mysql-wsrep-8.0/debian/dists/

**Comment by denisgcm** [comment]
Debian 11 is now supported by Galera Manager in version 1.5.0.
