### ISSUE TITLE
Galera Manager could not show Galera Node status

### ISSUE THREAD

**Issue by ajantonov** [codership/galera-manager-support#91]
Hi All,

We observe repeating issue, more than 3 times, with reflection status of Galera Node from a Galera Cluster.
![Galera Manager failed to show node 1 status](https://github.com/codership/galera-manager-support/assets/3727920/3d1a98c0-0dd9-4ad0-9053-66d676e23dd0)

Have in mind that Galera Cluster is working properly and nodes are exchanging their transactions.

Configuration:
Galera Manager
[OS] Ubuntu 22.04 LTS
[Version] 1.8.3

Galera Nodes :
Node 1. 
[OS] Ubuntu 22.04 LTS
[MARIADB] 10.11

Node 2. 
[OS] Ubuntu 22.04 LTS
[MARIADB] 10.11

Please tell us if you need more info from log files or something else !

Thank you in advance!

**Comment by byte** [comment]
@ajantonov is port 8081 being blocked by the firewall? for https, 9091 too.

**Comment by ajantonov** [comment]
> @ajantonov is port 8081 being blocked by the firewall? for https, 9091 too.

Thank you for the respons. It appears that 9091 is blocked!
